---
# tasks file for roles/loadbalancer
- name: Create template
  template:
    src: lb-config.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
    mode: 644
  notify: Restarte apach