--- # setup-lb.yml

- name: Configure loadbalancer
  hosts: loadbalancers
  become: true
  tasks:
  - name: Create template
    ansible.builtin.template:
      src: ../config/lb-config.j2
      dest: /etc/apache2/sites-available/000-default.conf
      owner: root
      group: root
      mode: 644
    notify: Restart apache

  handlers:
  - name: Restart apache
    ansible.builtin.service:
      name: apache2
      state: restarted